### ISSUE TITLE
File saved with JLD2 can't be read

### ISSUE THREAD

**Issue by sbromberger** [simonster/JLD2.jl#10]
Back on June 1, I saved a file using JLD2. Packages have been updated since then, and now I can't read the file back in:

```
julia> f = JLD2.jldopen("multiruns.jld","r")
ERROR: JLD2.InvalidDataException()
Stacktrace:
 [1] read(::JLD2.MmapIO, ::Type{JLD2.Superblock}) at /Users/seth/.julia/v0.6/JLD2/src/superblock.jl:25
 [2] jldopen(::String, ::Bool, ::Bool, ::Bool) at /Users/bromberger1/.julia/v0.6/JLD2/src/JLD2.jl:174
 [3] jldopen(::String, ::String) at /Users/bromberger1/.julia/v0.6/JLD2/src/JLD2.jl:220
```

Not sure what to do here.

```
phasebang:ca-condmat2$ ls -l multiruns.jld
-rw-r--r--  1 bromberger1  56797  1048613693 Jun  2 11:24 multiruns.jld
phasebang:ca-condmat2$ file multiruns.jld
multiruns.jld: data
phasebang:ca-condmat2$ head multiruns.jld
Julia data file (HDF5), version 0.2.0OHDR�>@6 name9parameters97
```

(JLD.jl can't read it either.)

**Comment by simonster** [comment]
This package is not yet released, so I make no guarantees regarding its ability to read files created with previous commits. But you should be able to check out an older commit, read the file, and save it in some other format.

**Comment by sbromberger** [comment]
Yeah, that's not gonna work: I checked out the version I was using previously and it no longer builds on 0.6. I'm pretty much hosed here.

**Comment by sbromberger** [comment]
@simonster - just wanted to check in now that you've released - in your opinion, is this package ready to be used as a dependency for MetaGraphs? (It would be awesome if so.)

**Comment by simonster** [comment]
Not sure. I'm not planning to change the format anymore, but I'm also not sure whether it's received enough use that I can be confident there aren't latent bugs that could lead to data corruption.

**Comment by timholy** [comment]
I've been using it a little and haven't yet had any trouble.
