### ISSUE TITLE
problem with JLD2.save

### ISSUE THREAD

**Issue by pevnak** [simonster/JLD2.jl#22]
I have a problem with the JLD.save as follows

> using JLD2
> x = x[1]
> JLD2.save("test.jld2","x",x)

according to docs, this should work, but I am having error

>ERROR: MethodError: no method matching save(::String, ::String, ::Array{Int64,1})
>Closest candidates are:
>  save(::FileIO.File{FileIO.DataFormat{:JLD2}}, ::AbstractString, ::Any, ::Any...; kwargs...) at >/Users/tpevny/.julia/v0.6/JLD2/src/loadsave.jl:98
>  save(::FileIO.File{FileIO.DataFormat{:JLD2}}, ::Any...; kwargs...) at >/Users/tpevny/.julia/v0.6/JLD2/src/loadsave.jl:110

Thanks for help

**Comment by simonster** [comment]
If you're on JLD2 master, you need to do `using FileIO` and call `save` (or `FileIO.save`) not `JLD2.save`. I don't really like it either.

**Comment by pevnak** [comment]
Thank you very much. It is little bit unintuitive,

**Comment by timholy** [comment]
https://github.com/JuliaIO/FileIO.jl/pull/43#r41086910. The bottom line is that not extending `FileIO.save` allows FileIO to support multiple packages that can read/write the same file format.

**Comment by cstjean** [comment]
It's probably been suggested, but why couldn't `JLD2.save`/`QuartzImageIO.save`/etc. be renamed `JLD2.save_impl`/etc.? Then these packages could safely reexport `FileIO.save`.

**Comment by timholy** [comment]
`_load` and `_save` were suggested in previous discussions. We could change that. The other way to go is https://github.com/JuliaLang/julia/issues/14472 (which I like better).
