### ISSUE TITLE
`load` and `save` should round-trip with groups

### ISSUE THREAD

**Issue by juliohm** [simonster/JLD2.jl#33]
First off, thanks for the package, really helpful :+1: 

I have a simple question, consider:

```julia
using FileIO

p1 = 1
p2 = 2.

data = [[1,2,3],[4.,5.,6.]]

save("foo.jld2", "params/p1", p1, "params/p2", p2, "data", data)
```

This will save the parameters in a group as expected. When I load it with `jldopen("foo.jld2","r")` and leave the file open, I have access to the parameters:

```julia
using JLD2

file = jldopen("foo.jld2","r")
p1 = file["params"]["p1"] # works fine
```

However, if I load the file with the FileIO interface, I get closed groups:

```julia
using FileIO

dict = load("foo.jld2")
dict["params"] # returns a closed group, no access to p1 nor p2
```

Is this expected behavior? Are we assuming that groups only work with the JLD2 interface?

**Comment by simonster** [comment]
I think the right behavior here is to load a Dict with keys named `params/p1`, `params/p2`, etc. so that `save(fname, load(fname))` saves a file with the same structure.

**Comment by juliohm** [comment]
Hi @simonster , I don't understand, you are saying that we shouldn't use the groups functionality explained in the docs?

**Comment by simonster** [comment]
I'm not going to change any of the documented group functionality.

**Comment by juliohm** [comment]
I am interpreting that I should stay away from groups then. Thank you, I am closing the issue.
