### ISSUE TITLE
Run femtocleaner

### ISSUE THREAD

**Issue by timholy** [simonster/JLD2.jl#44]

**Comment by timholy** [comment]
Didn't work. @simonster, can you activate femtocleaner? It will fix a huge number of depwarns on 0.7.

**Comment by timholy** [comment]
Thanks for the merge. Activating femtocleaner is as easy as visiting https://github.com/apps/femtocleaner and clicking "Configure." Two or three clicks later you're done.

More info:
https://github.com/JuliaComputing/FemtoCleaner.jl

**Comment by simonster** [comment]
It is activated (and has been since at least #29). Not sure why it didn't pick this up.
