### ISSUE TITLE
saving Array{Any,2}(80000,28)

### ISSUE THREAD

**Issue by sdmcallister** [simonster/JLD2.jl#47]
I have an array a = Array{Any,2}(80000,28) 
and do the following:

`f = jldopen("testfile.jld2","w")`
`for i in 1:28`
`f["dataset/var$i"]=a[:,i]`
`end`

This crashes my windows 10 and windows 7 pc running Julia 0.6. 

The issue doesn't occur if a = Array{String,2}, so I assume using the Any type is to be avoided.

**Comment by tpapp** [comment]
This works fine for me (`v0.6`, `JLD2` versions `0.0.4` and `master`):
```julia
using JLD2
a = rand([1, 1.0, "one", '1'], 80_000, 28)
f = jldopen("/tmp/testfile.jld2","w")
for i in indices(a, 2)
    f["dataset/var$i"]=a[:,i]
end
close(f)
```

**Comment by sdmcallister** [comment]
Thanks @tpapp.  Your code worked fine and now I can't seem to reproduce the error. The only difference was I used all strings.
