### ISSUE TITLE
JLD can't read files written by JLD2.

### ISSUE THREAD

**Issue by sbromberger** [simonster/JLD2.jl#7]
```
julia> z = load("multiruns2.jld","enron")
ERROR: unrecognized HDF5 datatype class 7
```
`multiruns2.jld` was the result of 
```
f = JLD2.jldopen("multiruns2.jld","w")
write(f, "enron", z)
close(f)
```

**Comment by simonster** [comment]
Compatibility with the original implementation of JLD is not a design goal of this package. (When JLD2 is merged into JLD, we will preserve the ability to read old JLD files, but old JLD readers will never be able to read JLD2 files.)

**Comment by sbromberger** [comment]
The README is a bit confusing, then:

> While other HDF5 implementations should be able to read the files it produces

**Comment by simonster** [comment]
JLD is not an HDF5 implementation.

**Comment by sbromberger** [comment]
> JLD is a specific "dialect" of HDF5

https://github.com/JuliaIO/JLD.jl/blob/master/README.md

(You can perhaps see how this might be confusing to a layperson like me.)
