### ISSUE TITLE
Reconstruction problem with Interpolants in v0.7.0

### ISSUE THREAD

**Issue by wg030** [simonster/JLD2.jl#99]
Right now I am moving my code from v0.6.4 to v.0.7.0 to test it for v.1.0.0.
I have figured out a reconstruction issue when I save and load an interpolant calculated wiht Interpolations package. Here is a minimal working example:

```
using JLD2, FileIO
using Interpolations


x = [-1, 0, 1, 2]
y = x.^2
intp = interpolate( (x,), y, Gridded( Linear()))
intp_orig = intp

@save "f.jld2" intp
@load "f.jld2" intp


println( "original: $(intp_orig[1.5])")
println( "reconstructed: $(intp[1.5])")
```

This code worked perfectly in v0.6.4, but now yields the warning
> ┌ Warning: type GriddedInterpolation{Float64,1,Int64,Gridded{Linear},Tuple{Array{Int64,1}},0} does not exist in workspace; reconstructing

and then causes the error

> ERROR: LoadError: MethodError: no method matching getindex(::getfield(JLD2.ReconstructedTypes, Symbol("##GriddedInterpolation{Float64,1,Int64,Gridded{Linear},Tuple{Array{Int64,1}},0}#368")), ::Float64)

in the last line of the code.
The issue might be related to the issue #82 , but I am not quite sure about that.

**Comment by timholy** [comment]
Interpolations has a major rewrite underway right now, so even if this gets fixed in JLD2 it will shortly break again. Your best bet is to load these files on 0.6.4, save the required info in a more durable format (e.g., the parent array and the options you used to construct the interpolation object).

Knowing what to do when types change is quite a nightmare.

**Comment by wg030** [comment]
Thanks for your answer, timholy.
Are there any rogh predictions for the point of time when the major rewrite of the Interpolations package is ready? So is it rather a question of one or two weeks or more likely a few months?
Because I a not sure if it makes sense to try to temporaily fix that problem since it is not that urgent.

**Comment by wg030** [comment]
With the latest update of the JLD2 package, my problem seems to have solved!
So I will close this issue!
